=== fashionweb/moraso/application/database/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="database">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="table"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="function"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="view"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="table">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="field"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="index"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="dataset"/>
      </xs:sequence>
      <xs:attribute name="engine" use="required" type="engine"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="since" use="required" type="comment"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="view">
    <xs:complexType mixed="true">
      <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="function">
    <xs:complexType mixed="true">
      <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="field">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="constraint"/>
      </xs:sequence>
      <xs:attribute name="autoincrement" type="xs:boolean"/>
      <xs:attribute name="default" use="required" type="xs:string"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="primary" type="xs:boolean"/>
      <xs:attribute name="type" use="required" type="xs:string"/>
      <xs:attribute name="nullable" use="optional" type="xs:boolean"/>
      <xs:attribute name="comment" use="optional" type="comment"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="dataset">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="record"/>
      </xs:sequence>
      <xs:attribute use="required" name="use" type="datasetuse"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="record">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="value"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="value">
    <xs:complexType mixed="true">
      <xs:attribute type="xs:string" use="required" name="attribute"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="constraint">
    <xs:complexType>
      <xs:attribute name="column" use="required" type="xs:string"/>
      <xs:attribute name="ondelete" use="required" type="ondeleteupdate"/>
      <xs:attribute name="onupdate" use="required" type="ondeleteupdate"/>
      <xs:attribute name="table" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="index">
    <xs:complexType>
      <xs:attribute name="columns" use="required" type="xs:string"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="type" use="required" type="indextype"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="engine">
    <xs:restriction base="xs:string">
      <xs:enumeration value="InnoDB"/>
      <xs:enumeration value="MyISAM"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ondeleteupdate">
    <xs:restriction base="xs:string">
      <xs:enumeration value="cascade"/>
      <xs:enumeration value="set null"/>
      <xs:enumeration value="no action"/>
      <xs:enumeration value="restrict"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="indextype">
    <xs:restriction base="xs:string">
      <xs:enumeration value="index"/>
      <xs:enumeration value="unique"/>
      <xs:enumeration value="fulltext"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="datasetuse">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ifempty"/>
      <xs:enumeration value="replace"/>
      <xs:enumeration value="add"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="comment">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="60"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== fashionweb/moraso/library/Moraso/Categorize/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">     
    <table name="art_has_categorization" engine="InnoDB">
        <field name="id_categorization" type="int(10) unsigned" default="null" autoincrement="true" primary="true" /> 
        
        <field name="id_art" type="int(10) unsigned" default="null" primary="true">
            <constraint table="art" column="idart" onupdate="restrict" ondelete="cascade"/>
        </field>
        
        <field name="id_category" type="int(10) unsigned" default="null" primary="true">
            <constraint table="categorization" column="id_category" onupdate="restrict" ondelete="cascade"/>
        </field>
    </table>
    
    <table name="categorization" engine="InnoDB">        
        <field name="id_category" type="int(10) unsigned" default="null" autoincrement="true" primary="true" /> 
        <field name="name" type="varchar(255)" default="null" />
    </table>
</database>

=== fashionweb/moraso/application/plugins/generic/utilities/tracking/.database.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="schema.xsd">
    <table name="tracking_customer" engine="InnoDB">
        <field name="customerid" type="int(10) unsigned" default="null" autoincrement="true"
            primary="true"/>
        <field name="identifier" type="varchar(255)" default="null"/>
        <field name="active" type="tinyint(4)" default="1"/>
    </table>
    <table name="tracking_project" engine="InnoDB">
        <field name="projectid" type="int(10) unsigned" default="null" autoincrement="true"
            primary="true"/>
        <field name="customerid" type="int(10) unsigned" default="null">
            <constraint table="tracking_customer" column="customerid" onupdate="restrict"
                ondelete="cascade"/>
        </field>
        <field name="identifier" type="varchar(255)" default="null"/>
        <field name="startdate" type="date" default="null"/>
        <field name="enddate" type="date" default="null"/>
        <index name="customerid" columns="customerid" unique="false"/>
    </table>
    <table name="tracking_track" engine="InnoDB">
        <field name="trackid" type="int(10) unsigned" default="null" autoincrement="true"
            primary="true"/>
        <field name="projectid" type="int(10) unsigned" default="null">
            <constraint table="tracking_project" column="projectid" onupdate="restrict"
                ondelete="cascade"/>
        </field>
        <field name="typeid" type="int(10) unsigned" default="null">
            <constraint table="tracking_type" column="typeid" onupdate="restrict"
                ondelete="set null"/>
        </field>
        <field name="userid" type="int(10) unsigned" default="null">
            <constraint table="acl_user" column="userid" onupdate="restrict" ondelete="cascade"/>
        </field>
        <field name="title" type="varchar(255)" default="null"/>
        <field name="description" type="text" default="null"/>
        <field name="closed" type="timestamp" default="null"/>
        <index name="typeid" columns="typeid" unique="false"/>
        <index name="projectid" columns="projectid" unique="false"/>
        <index name="userid" columns="userid" unique="false"/>
    </table>
    <table name="tracking_type" engine="InnoDB">
        <field name="typeid" type="int(10) unsigned" default="null" autoincrement="true"
            primary="true"/>
        <field name="identifier" type="varchar(255)" default="null"/>
    </table>
</database>

=== fashionweb/moraso/library/Fashionweb/Assets/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">  
    <table name="assets" engine="InnoDB" since="2.4.4-8">
        <field name="id" type="int(10) unsigned" default="null" autoincrement="true" primary="true" /> 
        <field name="idclient" type="int(10) unsigned" default="null"> 
            <constraint table="clients" column="idclient" onupdate="restrict" ondelete="cascade" />
        </field>
        <field name="headline" type="varchar(255)" />
        <field name="subheadline" type="varchar(255)" />
        <field name="text_1" type="text" />
        <field name="text_2" type="text" />
        <field name="created" type="timestamp" default="0000-00-00 00:00:00"/>
        <field name="lastmodified" type="timestamp on update current_timestamp" default="0000-00-00 00:00:00" />
        <field name="active" type="int(1) unsigned" default="0" />
    </table>
    
    <table name="assets_have_media" engine="InnoDB" since="2.4.4-8">
        <field name="id" type="int(10) unsigned" default="null" autoincrement="true" primary="true" /> 
        <field name="idasset" type="int(10) unsigned" default="null"> 
            <constraint table="assets" column="id" onupdate="restrict" ondelete="cascade" />
        </field>
        <field name="mediaid" type="int(10) unsigned" default="null">
            <constraint table="media" column="mediaid" onupdate="restrict" ondelete="cascade" />
        </field>
    </table>
</database>

=== fashionweb/moraso/library/Aitsu/Article/Policy/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../../application/database/schema.xsd">
    <table engine="InnoDB" name="policy" since="2.3.8">
        <field default="null" name="policyid" type="int(10) unsigned" nullable="false"
            primary="true" autoincrement="true"/>
        <field default="null" name="policy" type="varchar(255)" nullable="false"/>
        <index columns="policy" name="un_policy" type="unique"/>
    </table>
    <table engine="InnoDB" name="policy_default" since="2.3.8">
        <field default="null" name="policyid" type="int(10) unsigned" nullable="false"
            primary="true">
            <constraint column="policyid" ondelete="cascade" onupdate="restrict" table="policy"/>
        </field>
        <field default="null" name="idclient" type="int(10) unsigned" nullable="false"
            primary="true">
            <constraint column="idclient" ondelete="cascade" onupdate="restrict" table="clients"/>
        </field>
    </table>
    <table engine="InnoDB" name="policy_art_dependency" since="2.3.8">
        <field default="null" name="policyartid" type="int(10) unsigned" nullable="false"
            primary="true">
            <constraint column="policyartid" ondelete="cascade" onupdate="restrict"
                table="policy_art"/>
        </field>
        <field default="null" name="idartlang" type="int(10) unsigned" nullable="false"
            primary="true">
            <constraint column="idartlang" ondelete="cascade" onupdate="restrict" table="art_lang"/>
        </field>
    </table>
    <table engine="InnoDB" name="policy_art" since="2.3.8">
        <field default="null" name="policyartid" type="int(10) unsigned" nullable="false"
            primary="true" autoincrement="true"/>
        <field default="null" name="idartlang" type="int(10) unsigned" nullable="false">
            <constraint column="idartlang" ondelete="cascade" onupdate="restrict" table="art_lang"/>
        </field>
        <field default="null" name="policyid" type="int(10) unsigned" nullable="false">
            <constraint column="policyid" ondelete="cascade" onupdate="restrict" table="policy"/>
        </field>
        <field default="0" name="status" type="tinyint(4)" nullable="false"/>
        <field default="null" name="message" type="varchar(255)" nullable="true"/>
        <field default="null" name="lastcheck" type="timestamp" nullable="true"/>
        <field default="null" name="nextcheck" type="timestamp" nullable="true"/>
        <index columns="idartlang,policyid" name="key_candidate" type="unique"/>
    </table>
</database>

=== fashionweb/moraso/library/Webtischlerei/Eav/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">     
    <table name="eav_entity" engine="InnoDB" since="">
        <field name="entity_id" type="int(10) unsigned" default="null" autoincrement="true" primary="true" /> 
    </table>

    <table name="eav_entity_attribute" engine="InnoDB" since="">
        <field name="entity_attribute_id" type="int(10) unsigned" default="null" autoincrement="true" primary="true" /> 
        
        <field name="entity_id" type="int(10) unsigned" default="null"> 
            <constraint table="eav_entity" column="entity_id" onupdate="restrict" ondelete="cascade"/>
        </field>

        <field name="attribute_id" type="int(10) unsigned" default="null"> 
            <constraint table="eav_attribute" column="attribute_id" onupdate="restrict" ondelete="cascade"/>
        </field>
    </table>
    
    <table name="eav_attribute" engine="InnoDB" since="">
        <field name="attribute_id" type="int(10) unsigned" default="null" autoincrement="true" primary="true" /> 
        <field name="attribute_alias" type="varchar(255)" default="null" />
        <field name="attribute_set_id" type="int(10) unsigned" default="null">
            <constraint table="eav_attribute_set" column="attribute_set_id" onupdate="restrict" ondelete="cascade"/>
        </field>
    </table>
    
    <table name="eav_attribute_set" engine="InnoDB" since="">
        <field name="attribute_set_id" type="int(10) unsigned" default="null" autoincrement="true" primary="true" /> 
        <field name="attribute_set_name" type="varchar(255)" default="null" />
    </table>
 
    <table name="eav_value" engine="InnoDB" since="">
        <field name="value_id" type="int(10) unsigned" default="null" autoincrement="true" primary="true" /> 
        
        <field name="entity_attribute_id" type="int(10) unsigned" default="null"> 
            <constraint table="eav_entity_attribute" column="entity_attribute_id" onupdate="restrict" ondelete="cascade"/>
        </field>
    </table>
    
    <table name="eav_value_string" engine="InnoDB" since="">
        <field name="value_id" type="int(10) unsigned" default="null" primary="true">
            <constraint table="eav_value" column="value_id" onupdate="restrict" ondelete="cascade"/>
        </field>
        <field name="value" type="varchar(255)" default="null" />
    </table>
    
    <table name="eav_value_integer" engine="InnoDB" since="">
        <field name="value_id" type="int(10) unsigned" default="null" primary="true">
            <constraint table="eav_value" column="value_id" onupdate="restrict" ondelete="cascade"/>
        </field>
        <field name="value" type="int" default="null" />
    </table>
    
    <table name="eav_value_float" engine="InnoDB" since="">
        <field name="value_id" type="int(10) unsigned" default="null" primary="true">
            <constraint table="eav_value" column="value_id" onupdate="restrict" ondelete="cascade"/>
        </field>
        <field name="value" type="float" default="null" />
    </table>
</database>

=== fashionweb/moraso/library/Aitsu/Service/Google/Geocode/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../../../application/database/schema.xsd">
    <table engine="InnoDB" name="google_geolocation" since="2.3.8-8">
        <field default="null" name="id" type="int(10) unsigned" nullable="false"
            autoincrement="true" primary="true"/>
        <field default="null" name="address" type="text" nullable="false"/>
        <field default="null" name="hash" type="varchar(32)" nullable="false"/>
        <field default="null" name="lat" type="float" nullable="true"/>
        <field default="null" name="lng" type="float" nullable="true"/>
        <field default="current_timestamp" name="requested" type="timestamp" nullable="false"/>
        <index columns="hash" name="un_hash" type="unique"/>
        <index columns="lat" name="lat" type="index"/>
        <index columns="lng" name="lng" type="index"/>
        <index columns="lat,lng" name="lng_lng" type="index"/>
    </table>
</database>

=== fashionweb/moraso/library/Moraso/Nodes/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">     
    <table name="nodes" engine="InnoDB">
        <field name="node_id" type="int(10) unsigned" default="null" autoincrement="true" primary="true" /> 
        
        <field name="public" type="varchar(255)" nullable="false" default="1" />
        <field name="active" type="varchar(255)" nullable="false" default="0" />
        
        <field name="lft" type="int(10) unsigned" nullable="false" default="null" />
        <field name="rgt" type="int(10) unsigned" nullable="false" default="null" />
        
        
        <index name="public" columns="public" type="index" />
        <index name="active" columns="active" type="index" />
        
        <index columns="lft,rgt" name="un_lft_rgt" type="unique" />
    </table>
</database>

=== fashionweb/moraso/library/Fashionweb/Events/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">  
    <table name="events" engine="InnoDB" since="">
        <field name="idevent" type="int(10) unsigned" default="null" autoincrement="true" primary="true" /> 
        <field name="idclient" type="int(10) unsigned" default="null"> 
            <constraint table="clients" column="idclient" onupdate="restrict" ondelete="cascade" />
        </field>
        <field name="idorganizer" type="int(10) unsigned" default="null"> 
            <constraint table="events_organizer" column="idorganizer" onupdate="restrict" ondelete="cascade" />
        </field>
        <field name="idcategory" type="int(10) unsigned" default="null">
            <constraint table="events_categories" column="idcategory" onupdate="restrict" ondelete="cascade" />
        </field>
        <field name="title" type="varchar(255)" />
        <field name="text" type="text" />
        <field name="created" type="timestamp" default="0000-00-00 00:00:00"/>
        <field name="lastmodified" type="timestamp on update current_timestamp" default="0000-00-00 00:00:00" />
        <field name="active" type="int(1) unsigned" default="0" />
        <field name="starttime" type="timestamp" default="0000-00-00 00:00:00" />
        <field name="endtime" type="timestamp" default="0000-00-00 00:00:00" />
        <field name="place" type="varchar(255)" />
        <field name="place_details" type="text" />
    </table>
           
    <table name="events_organizer" engine="InnoDB" since="">
        <field name="idorganizer" type="int(10) unsigned" default="null" autoincrement="true" primary="true" /> 
        <field name="name" type="varchar(255)" />
        <field name="phone" type="varchar(255)" />
        <field name="email" type="varchar(255)" />
        <field name="homepage" type="varchar(255)" />
    </table>
           
    <table name="events_has_media" engine="InnoDB" since="2.4.4-8">
        <field name="id" type="int(10) unsigned" default="null" autoincrement="true" primary="true" /> 
        <field name="idevent" type="int(10) unsigned" default="null"> 
            <constraint table="events" column="idevent" onupdate="restrict" ondelete="cascade" />
        </field>
        <field name="mediaid" type="int(10) unsigned" default="null">
            <constraint table="media" column="mediaid" onupdate="restrict" ondelete="cascade" />
        </field>
    </table>

    <table name="events_categories" engine="InnoDB" since="">
        <field name="idcategory" type="int(10) unsigned" default="null" autoincrement="true" primary="true" /> 
        <field name="name" type="varchar(255)" />
        <index columns="name" name="name" type="unique"/>
        <dataset use="ifempty">
            <record>
                <value attribute="idcategory">1</value>
                <value attribute="name">Kategorie A</value>
            </record>
            <record>
                <value attribute="idcategory">2</value>
                <value attribute="name">Kategorie B</value>
            </record>
            <record>
                <value attribute="idcategory">3</value>
                <value attribute="name">Kategorie C</value>
            </record>
        </dataset>
    </table>
</database>
