=== fashionweb/moraso/application/database/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="database">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="table"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="function"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="view"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="table">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="field"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="index"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="dataset"/>
      </xs:sequence>
      <xs:attribute name="engine" use="required" type="engine"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="since" use="required" type="comment"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="view">
    <xs:complexType mixed="true">
      <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="function">
    <xs:complexType mixed="true">
      <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="field">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="constraint"/>
      </xs:sequence>
      <xs:attribute name="autoincrement" type="xs:boolean"/>
      <xs:attribute name="default" use="required" type="xs:string"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="primary" type="xs:boolean"/>
      <xs:attribute name="type" use="required" type="xs:string"/>
      <xs:attribute name="nullable" use="optional" type="xs:boolean"/>
      <xs:attribute name="comment" use="optional" type="comment"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="dataset">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="record"/>
      </xs:sequence>
      <xs:attribute use="required" name="use" type="datasetuse"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="record">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="value"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="value">
    <xs:complexType mixed="true">
      <xs:attribute type="xs:string" use="required" name="attribute"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="constraint">
    <xs:complexType>
      <xs:attribute name="column" use="required" type="xs:string"/>
      <xs:attribute name="ondelete" use="required" type="ondeleteupdate"/>
      <xs:attribute name="onupdate" use="required" type="ondeleteupdate"/>
      <xs:attribute name="table" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="index">
    <xs:complexType>
      <xs:attribute name="columns" use="required" type="xs:string"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="type" use="required" type="indextype"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="engine">
    <xs:restriction base="xs:string">
      <xs:enumeration value="InnoDB"/>
      <xs:enumeration value="MyISAM"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ondeleteupdate">
    <xs:restriction base="xs:string">
      <xs:enumeration value="cascade"/>
      <xs:enumeration value="set null"/>
      <xs:enumeration value="no action"/>
      <xs:enumeration value="restrict"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="indextype">
    <xs:restriction base="xs:string">
      <xs:enumeration value="index"/>
      <xs:enumeration value="unique"/>
      <xs:enumeration value="fulltext"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="datasetuse">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ifempty"/>
      <xs:enumeration value="replace"/>
      <xs:enumeration value="add"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="comment">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="60"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== fashionweb/moraso/application/plugins/generic/management/rewritehistory/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="schema.xsd">
    <table name="rewrite_history" engine="InnoDB" since="2.2.1.1">
        <field name="id" type="int(10) unsigned" default="null" autoincrement="true"
            primary="true"/>
        <field name="idclient" type="int(10) unsigned" default="0"
            comment="Client, the entry belongs to.">
            <constraint table="clients" column="idclient" onupdate="no action" ondelete="cascade"/>
        </field>
        <field name="url" type="varchar(255)" default="null" 
            comment="Full URL of the article with the specified idartlang."/>
        <field name="target" type="varchar(255)" default="null" 
            comment="The article or category the entity belongs to."/>
        <field default="0" name="manualentry" type="tinyint(4) unsigned"
            comment="1 indicates a manual entry made with the plugin."/>
        <field name="created" type="datetime" default="null"/>
    </table>
</database>

=== fashionweb/moraso/application/plugins/article/timecontrol/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../../application/database/schema.xsd">
    <table engine="InnoDB" name="art_timecontrol" since="2.3.12">
        <field default="null" name="idartlang" type="int(10) unsigned" nullable="false"
            primary="true">
            <constraint column="idartlang" ondelete="cascade" onupdate="restrict" table="art_lang"/>
        </field>
        <field default="null" name="timea" type="datetime" nullable="true"/>
        <field default="null" name="statusa" type="tinyint(1)" nullable="false"/>
        <field default="null" name="timeb" type="datetime" nullable="true"/>
        <field default="null" name="statusb" type="tinyint(1)" nullable="false"/>
    </table>
</database>

=== fashionweb/moraso/library/Moraso/Cart/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">     
    <table name="cart_order" engine="InnoDB">
        <field name="order_id" type="int(10) unsigned" default="null" autoincrement="true" primary="true" /> 
        <field name="payment_method" type="varchar(255)" default="cash"  nullable="false" /> 
        <field name="payed" type="int(1) unsigned" default="null" nullable="true" />
        <field name="ordered" type="int(1) unsigned" default="null" nullable="true" />
        <field name="additional_info" type="text" default="null" nullable="true" /> 
        <field name="timestamp" type="timestamp" default="CURRENT_TIMESTAMP" nullable="false" />
        
        <index name="payed" columns="payed" type="index" />
        <index name="ordered" columns="ordered" type="index" />
        <index name="timestamp" columns="timestamp" type="index" />
    </table>
    
    <table name="cart_order_has_article" engine="InnoDB">
        <field name="id" type="int(10) unsigned" autoincrement="true" primary="true" default="null" /> 
        <field name="order_id" type="int(10) unsigned" primary="true" default="null">
            <constraint table="cart_order" column="order_id" onupdate="restrict" ondelete="cascade"/>
        </field>
        <field name="article_id" type="int(10) unsigned" default="null">
            <constraint table="art" column="idart" onupdate="restrict" ondelete="cascade"/>
        </field>  
        <field name="qty" type="int(10) unsigned" default="1"  nullable="false" /> 
        <field name="timestamp" type="timestamp" default="CURRENT_TIMESTAMP" nullable="false" />
    </table>
    
    <table name="cart_order_has_customer" engine="InnoDB">
        <field name="id" type="int(10) unsigned" autoincrement="true" primary="true" default="null" /> 
        <field name="order_id" type="int(10) unsigned" primary="true" default="null">
            <constraint table="cart_order" column="order_id" onupdate="restrict" ondelete="cascade"/>
        </field>
        <field name="customer_id" type="int(10) unsigned" default="null">
            <constraint table="acl_user" column="userid" onupdate="restrict" ondelete="cascade"/>
        </field>  
        
        <field name="delivery_title" type="varchar(255)" default="null" nullable="false" /> 
        <field name="delivery_firstname" type="varchar(255)" default="null" nullable="false" /> 
        <field name="delivery_secondname" type="varchar(255)" default="null" nullable="false" /> 
        <field name="delivery_lastname" type="varchar(255)" default="null" nullable="false" /> 
        <field name="delivery_street" type="varchar(255)" default="null" nullable="false" /> 
        <field name="delivery_housenumber" type="varchar(255)" default="null" nullable="false" /> 
        <field name="delivery_postal_code" type="varchar(255)" default="null" nullable="false" /> 
        <field name="delivery_city" type="varchar(255)" default="null" nullable="false" /> 
        <field name="delivery_telephone" type="varchar(255)" default="null" nullable="false" /> 
        <field name="delivery_fax" type="varchar(255)" default="null" nullable="false" /> 
        <field name="delivery_email" type="varchar(255)" default="null" nullable="false" /> 
        <field name="billing_title" type="varchar(255)" default="null" nullable="false" /> 
        <field name="billing_firstname" type="varchar(255)" default="null" nullable="false" /> 
        <field name="billing_secondname" type="varchar(255)" default="null" nullable="false" /> 
        <field name="billing_lastname" type="varchar(255)" default="null" nullable="false" /> 
        <field name="billing_street" type="varchar(255)" default="null" nullable="false" /> 
        <field name="billing_housenumber" type="varchar(255)" default="null" nullable="false" /> 
        <field name="billing_postal_code" type="varchar(255)" default="null" nullable="false" /> 
        <field name="billing_city" type="varchar(255)" default="null" nullable="false" /> 
        <field name="billing_telephone" type="varchar(255)" default="null" nullable="false" /> 
        <field name="billing_fax" type="varchar(255)" default="null" nullable="false" /> 
        <field name="billing_email" type="varchar(255)" default="null" nullable="false" /> 
    </table>
</database>

=== fashionweb/moraso/library/Moraso/Plugin/Addresses/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <table name="addresses" engine="InnoDB" since="">
        <field name="address_id" type="int(10) unsigned" default="null" autoincrement="true" primary="true" />
        <field name="name" type="varchar(255)" nullable="true" default="null" />
        <field name="street" type="varchar(255)" nullable="true" default="null" />
        <field name="house_number" type="varchar(255)" nullable="true" default="null" />
        <field name="postal_code" type="int(5) unsigned" default="null" nullable="false" />
        <field name="city" type="varchar(255)" default="null" />
                
        <!-- Indexe setzen -->
        <index name="index_name" columns="name" type="index" />
        <index name="index_street" columns="street" type="index" />
        <index name="index_house_number" columns="house_number" type="index" />
        <index name="index_postal_code" columns="postal_code" type="index" />
        <index name="index_city" columns="city" type="index" />
    </table>
    
    <table name="addresses_groups" engine="InnoDB" since="">
        <field name="addresses_group_id" type="int(10) unsigned" default="null" autoincrement="true" primary="true" />
        <field name="name" type="varchar(255)" nullable="true" default="null" />
                 
        <!-- Indexe setzen -->
        <index name="index_name" columns="name" type="index" />
        
        <!-- Basiswerte -->
        <dataset use="ifempty">
            <record>
                <value attribute="addresses_group_id">1</value>
                <value attribute="name">Group #1</value>
            </record>
            <record>
                <value attribute="addresses_group_id">2</value>
                <value attribute="name">Group #2</value>
            </record>
        </dataset>
    </table>
    
    <table name="addresses_address_has_group" engine="InnoDB" since="">
        <field name="address_id" type="int(10) unsigned" default="null" primary="false">
            <constraint table="addresses" column="address_id" onupdate="restrict" ondelete="cascade" />
        </field>
        
         <field name="addresses_group_id" type="int(10) unsigned" default="null" primary="false">
            <constraint table="addresses_groups" column="addresses_group_id" onupdate="restrict" ondelete="cascade" />
        </field>
        
        <!-- Indexe setzen -->
        <index name="un_address_group" columns="address_id,addresses_group_id" type="unique" />
    </table>
    
    <table name="addresses_google_data" engine="InnoDB" since="">
        <field name="address_id" type="int(10) unsigned" default="null" primary="true">
            <constraint table="addresses" column="address_id" onupdate="restrict" ondelete="cascade" />
        </field>
        
        <field name="lat" type="double" nullable="false" default="null" />
        <field name="lng" type="double" nullable="false" default="null" />
        
        <field name="street_address" type="varchar(255)" nullable="true" default="null" />
        <field name="route" type="varchar(255)" nullable="true" default="null" />
        <field name="intersection" type="varchar(255)" nullable="true" default="null" />
        <field name="political" type="varchar(255)" nullable="true" default="null" />
        <field name="country" type="varchar(255)" nullable="true" default="null" />
        <field name="administrative_area_level_1" type="varchar(255)" nullable="true" default="null" />
        <field name="administrative_area_level_2" type="varchar(255)" nullable="true" default="null" />
        <field name="administrative_area_level_3" type="varchar(255)" nullable="true" default="null" />
        <field name="colloquial_area" type="varchar(255)" nullable="true" default="null" />
        <field name="locality" type="varchar(255)" nullable="true" default="null" />
        <field name="sublocality" type="varchar(255)" nullable="true" default="null" />
        <field name="neighborhood" type="varchar(255)" nullable="true" default="null" />
        <field name="premise" type="varchar(255)" nullable="true" default="null" />
        <field name="subpremise" type="varchar(255)" nullable="true" default="null" />
        <field name="postal_code" type="varchar(255)" nullable="true" default="null" />
        <field name="natural_feature" type="varchar(255)" nullable="true" default="null" />
        <field name="airport" type="varchar(255)" nullable="true" default="null" />
        <field name="park" type="varchar(255)" nullable="true" default="null" />
        <field name="point_of_interest" type="varchar(255)" nullable="true" default="null" />
        <field name="post_box" type="varchar(255)" nullable="true" default="null" />
        <field name="street_number" type="varchar(255)" nullable="true" default="null" />
        <field name="floor" type="varchar(255)" nullable="true" default="null" />
        <field name="room" type="varchar(255)" nullable="true" default="null" />
        
        <!-- Indexe setzen -->
        <index name="index_lat" columns="lat" type="index" />
        <index name="index_lng" columns="lng" type="index" />
    </table>
</database>

=== fashionweb/moraso/library/Moraso/Config/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <table engine="InnoDB" name="moraso_config" since="1.5.0">
        <field name="id" type="int(10) unsigned" nullable="false" default="null"  primary="true" autoincrement="true" />
        <field name="config" type="varchar (255)" />
        <field name="env" type="varchar (255)" />
        <field name="identifier" type="varchar (255)" />
        <field name="value" type="varchar (255)" />
        
        <index columns="config,env,identifier" type="unique" name="un_config_env_identifier" />
    </table>
</database>

=== fashionweb/moraso/application/modules/Custom/IsaBern/Address/.database.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/home/kummer/workspace/org.aitsu.dev/application/database/schema.xsd">
    <table engine="InnoDB" name="isabern_adresse" since="IsaBern Adressen 1.0">
        <field default="null" name="id" type="int(10) unsigned" nullable="false" primary="true"/>
        <field default="null" name="firma" type="varchar(255)" nullable="true"/>
        <field default="null" name="strasse" type="varchar(255)" nullable="true"/>
        <field default="null" name="plz" type="varchar(10)" nullable="true"/>
        <field default="null" name="ort" type="varchar(255)" nullable="true"/>
        <field default="null" name="nachname" type="varchar(255)" nullable="true"/>
        <field default="null" name="vorname" type="varchar(255)" nullable="true"/>
        <field default="null" name="modified" type="datetime" nullable="false"/>
    </table>
    <table engine="InnoDB" name="isabern_kategorie" since="IsaBern Adressen 1.0">
        <field default="null" name="id" type="int(10) unsigned" nullable="false" primary="true"/>
        <field default="null" name="bezeichner" type="varchar(255)" nullable="false"/>
        <field default="null" name="modified" type="datetime" nullable="false"/>
    </table>
    <table engine="InnoDB" name="isabern_rubrik" since="IsaBern Adressen 1.0">
        <field default="null" name="id" type="int(10) unsigned" nullable="false" primary="true"/>
        <field default="null" name="bezeichner" type="varchar(255)" nullable="false"/>
        <field default="null" name="kategorie" type="int(10) unsigned" nullable="true">
            <constraint column="id" ondelete="cascade" onupdate="no action"
                table="isabern_kategorie"/>
        </field>
        <field default="null" name="modified" type="datetime" nullable="false"/>
    </table>
    <table engine="InnoDB" name="isabern_angebot" since="IsaBern Adressen 1.0">
        <field default="null" name="id" type="int(10) unsigned" nullable="false" primary="true"/>
        <field default="null" name="bezeichner" type="varchar(255)" nullable="false"/>
        <field default="null" name="modified" type="datetime" nullable="false"/>
    </table>
    <table engine="InnoDB" name="isabern_adresse_angebot" since="IsaBern Adressen 1.0">
        <field default="null" name="adresse" type="int(10) unsigned" nullable="false" primary="true">
            <constraint column="id" ondelete="cascade" onupdate="no action" table="isabern_adresse"
            />
        </field>
        <field default="null" name="angebot" type="int(10) unsigned" nullable="false" primary="true">
            <constraint column="id" ondelete="cascade" onupdate="no action" table="isabern_angebot"
            />
        </field>
        <field default="null" name="modified" type="datetime" nullable="false"/>
    </table>
    <table engine="InnoDB" name="isabern_zielgruppe" since="IsaBern Adressen 1.0">
        <field default="null" name="id" type="int(10) unsigned" nullable="false" primary="true"/>
        <field default="null" name="bezeichner" type="varchar(255)" nullable="false"/>
        <field default="null" name="modified" type="datetime" nullable="false"/>
    </table>
    <table engine="InnoDB" name="isabern_adresse_zielgruppe" since="IsaBern Adressen 1.0">
        <field default="null" name="adresse" type="int(10) unsigned" nullable="false" primary="true">
            <constraint column="id" ondelete="cascade" onupdate="no action" table="isabern_adresse"
            />
        </field>
        <field default="null" name="zielgruppe" type="int(10) unsigned" nullable="false"
            primary="true">
            <constraint column="id" ondelete="cascade" onupdate="no action"
                table="isabern_zielgruppe"/>
        </field>
        <field default="null" name="modified" type="datetime" nullable="false"/>
    </table>
    <table engine="InnoDB" name="isabern_adresse_katgorie_rubrik" since="IsaBern Adressen 1.0">
        <field default="null" name="adresse" type="int(10) unsigned" nullable="false" primary="true">
            <constraint column="id" ondelete="cascade" onupdate="no action" table="isabern_adresse"
            />
        </field>
        <field default="null" name="kategorie" type="int(10) unsigned" nullable="false"
            primary="true">
            <constraint column="id" ondelete="cascade" onupdate="no action"
                table="isabern_kategorie"/>
        </field>
        <field default="null" name="rubrik" type="int(10) unsigned" nullable="false" primary="true">
            <constraint column="id" ondelete="cascade" onupdate="no action" table="isabern_rubrik"/>
        </field>
        <field default="null" name="modified" type="datetime" nullable="false"/>
    </table>
</database>

=== fashionweb/moraso/library/Fashionweb/Bookingsystem/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">  
    <table name="bookings" engine="InnoDB" since="">
        <field name="id_request" type="int(10) unsigned" default="null" autoincrement="true" primary="true" /> 
        <field name="id_requestor" type="int(10) unsigned" default="null" />
        <field name="ts_request" type="timestamp" default="CURRENT_TIMESTAMP" />
        <field name="status" type="enum('1', '2', '3')" default="1" />
        <field name="date_from" type="date" default="null" nullable="true" />
        <field name="date_until" type="date" default="null" nullable="true" />
        <field name="people" type="enum('1', '2', '3', '4')" default="1" />
    </table>
    
    <table name="bookings_requestor" engine="InnoDB" since="">
        <field name="id_requestor" type="int(10) unsigned" default="null" autoincrement="true" primary="true" /> 
        <field name="last_name" type="varchar(255)" />
        <field name="first_name" type="varchar(255)" />
        <field name="road" type="varchar(255)" />
        <field name="house_number" type="varchar(255)" />
        <field name="postal_code" type="varchar(255)" />
        <field name="city" type="varchar(255)" />
        <field name="country" type="varchar(255)" />
        <field name="phone" type="varchar(255)" />
        <field name="email" type="varchar(255)" />
    </table>
</database>

=== fashionweb/moraso/library/Moraso/Plugin/Placeholder/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="schema.xsd">
    <table name="placeholder" engine="InnoDB" since="2.3.0.1">
        <field name="id" type="int(10) unsigned" default="null" autoincrement="true" primary="true" />
        <field name="identifier" type="varchar(255)" default="null" />
    </table>
    
    <table name="placeholder_values" engine="InnoDB" since="2.3.0.1">
        <field name="id" type="int(10) unsigned" default="null" autoincrement="true" primary="true" />
        <field name="placeholderid" type="int(10) unsigned" default="null">
            <constraint table="placeholder" column="id" onupdate="restrict" ondelete="cascade"/>
        </field>
        <field name="idlang" type="int(10) unsigned" default="null">
            <constraint table="lang" column="idlang" onupdate="restrict" ondelete="cascade"/>
        </field>
        <field name="value" type="text" default="null" />
    </table>
</database>
