=== fashionweb/moraso/application/database/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="database">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="table"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="function"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="view"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="table">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="field"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="index"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="dataset"/>
      </xs:sequence>
      <xs:attribute name="engine" use="required" type="engine"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="since" use="required" type="comment"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="view">
    <xs:complexType mixed="true">
      <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="function">
    <xs:complexType mixed="true">
      <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="field">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="constraint"/>
      </xs:sequence>
      <xs:attribute name="autoincrement" type="xs:boolean"/>
      <xs:attribute name="default" use="required" type="xs:string"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="primary" type="xs:boolean"/>
      <xs:attribute name="type" use="required" type="xs:string"/>
      <xs:attribute name="nullable" use="optional" type="xs:boolean"/>
      <xs:attribute name="comment" use="optional" type="comment"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="dataset">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="record"/>
      </xs:sequence>
      <xs:attribute use="required" name="use" type="datasetuse"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="record">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="value"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="value">
    <xs:complexType mixed="true">
      <xs:attribute type="xs:string" use="required" name="attribute"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="constraint">
    <xs:complexType>
      <xs:attribute name="column" use="required" type="xs:string"/>
      <xs:attribute name="ondelete" use="required" type="ondeleteupdate"/>
      <xs:attribute name="onupdate" use="required" type="ondeleteupdate"/>
      <xs:attribute name="table" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="index">
    <xs:complexType>
      <xs:attribute name="columns" use="required" type="xs:string"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="type" use="required" type="indextype"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="engine">
    <xs:restriction base="xs:string">
      <xs:enumeration value="InnoDB"/>
      <xs:enumeration value="MyISAM"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ondeleteupdate">
    <xs:restriction base="xs:string">
      <xs:enumeration value="cascade"/>
      <xs:enumeration value="set null"/>
      <xs:enumeration value="no action"/>
      <xs:enumeration value="restrict"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="indextype">
    <xs:restriction base="xs:string">
      <xs:enumeration value="index"/>
      <xs:enumeration value="unique"/>
      <xs:enumeration value="fulltext"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="datasetuse">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ifempty"/>
      <xs:enumeration value="replace"/>
      <xs:enumeration value="add"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="comment">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="60"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== fashionweb/moraso/library/Wdrei/Shop/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../application/database/schema.xsd">
    <table engine="InnoDB" name="shop_currency" since="2.4.0">
        <field default="null" name="currencyid" type="int(10) unsigned" nullable="false"
            primary="true" autoincrement="true"/>
        <field default="null" name="code" type="varchar(10)" nullable="false"/>
        <field default="null" name="parity" type="float" nullable="false"/>
        <dataset use="ifempty">
            <record>
                <value attribute="code">CHF</value>
                <value attribute="parity">1</value>
            </record>
            <record>
                <value attribute="code">EUR</value>
                <value attribute="parity">1</value>
            </record>
            <record>
                <value attribute="code">USD</value>
                <value attribute="parity">1</value>
            </record>
        </dataset>
    </table>
    <table engine="InnoDB" name="shop_tax_class" since="2.4.0">
        <field default="null" name="classid" type="int(10) unsigned" nullable="false" primary="true"
            autoincrement="true"/>
        <field default="null" name="identifier" type="varchar(255)" nullable="false"/>
        <dataset use="ifempty">
            <record>
                <value attribute="identifier">normal</value>
            </record>
            <record>
                <value attribute="identifier">reduced</value>
            </record>
        </dataset>
    </table>
    <table engine="InnoDB" name="shop_tax_rate" since="2.4.0">
        <field default="null" name="classid" type="int(10) unsigned" nullable="false" primary="true">
            <constraint column="classid" ondelete="cascade" onupdate="restrict"
                table="shop_tax_class"/>
        </field>
        <field default="null" name="countryid" type="int(10) unsigned" nullable="false"
            primary="true">
            <constraint column="countryid" ondelete="cascade" onupdate="restrict"
                table="geo_country"/>
        </field>
        <field default="0" name="rate" type="float" nullable="false"/>
    </table>
    <table engine="InnoDB" name="shop_product" since="2.4.0">
        <field default="null" name="productid" type="int(10) unsigned" nullable="false"
            primary="true" autoincrement="true"/>
        <field default="null" name="idart" type="int(10) unsigned" nullable="false">
            <constraint column="idart" ondelete="cascade" onupdate="restrict" table="art_lang"/>
        </field>
        <field default="null" name="sku" type="varchar(255)" nullable="true"/>
        <field default="null" name="price" type="float" nullable="true"/>
        <field default="null" name="classid" type="int(10) unsigned" nullable="false">
            <constraint column="classid" ondelete="restrict" onupdate="restrict"
                table="shop_tax_class"/>
        </field>
        <field default="0" name="vatincluded" type="int(4)" nullable="false"/>
        <field default="0" name="variableprice" type="int(4)" nullable="false"/>
        <field default="null" name="currencyid" type="int(10) unsigned" nullable="false">
            <constraint column="currencyid" ondelete="restrict" onupdate="restrict"
                table="shop_currency"/>
        </field>
        <field default="normal" name="shippingcharge" type="enum('normal','always','never')"
            nullable="false"/>
        <field default="never" name="additionalinfo" type="enum('allowed','always','never')"
            nullable="false"/>
    </table>
    <table engine="InnoDB" name="shop_product_name" since="2.4.0">
        <field default="null" name="productid" type="int(10) unsigned" nullable="false"
            primary="true">
            <constraint column="productid" ondelete="cascade" onupdate="restrict"
                table="shop_product"/>
        </field>
        <field default="null" name="idlang" type="int(10) unsigned" nullable="false" primary="true">
            <constraint column="idlang" ondelete="cascade" onupdate="restrict" table="lang"/>
        </field>
        <field default="null" name="name" type="varchar(255)" nullable="true"/>
        <field default="null" name="description" type="text" nullable="true"/>
    </table>
    <table engine="InnoDB" name="shop_order" since="2.4.0">
        <field default="null" name="orderid" type="int(10) unsigned" nullable="false" primary="true"
            autoincrement="true"/>
        <field default="current_timestamp" name="created" type="timestamp" nullable="false"/>
        <field default="null" name="checkedout" type="timestamp" nullable="true"/>
        <field default="null" name="firstname" type="varchar(255)" nullable="true"/>
        <field default="null" name="lastname" type="varchar(255)" nullable="true"/>
        <field default="null" name="company" type="varchar(255)" nullable="true"/>
        <field default="null" name="street" type="varchar(255)" nullable="true"/>
        <field default="null" name="zip" type="varchar(20)" nullable="true"/>
        <field default="null" name="city" type="varchar(255)" nullable="true"/>
        <field default="null" name="countryid" type="int(10) unsigned" nullable="true">
            <constraint column="countryid" ondelete="restrict" onupdate="restrict"
                table="geo_country"/>
        </field>
        <field default="null" name="ifirstname" type="varchar(255)" nullable="true"/>
        <field default="null" name="ilastname" type="varchar(255)" nullable="true"/>
        <field default="null" name="icompany" type="varchar(255)" nullable="true"/>
        <field default="null" name="istreet" type="varchar(255)" nullable="true"/>
        <field default="null" name="izip" type="varchar(20)" nullable="true"/>
        <field default="null" name="icity" type="varchar(255)" nullable="true"/>
        <field default="null" name="icountryid" type="int(10) unsigned" nullable="true">
            <constraint column="countryid" ondelete="restrict" onupdate="restrict"
                table="geo_country"/>
        </field>
    </table>
    <table engine="InnoDB" name="shop_item" since="2.4.0">
        <field default="null" name="itemid" type="int(10) unsigned" nullable="false" primary="true"
            autoincrement="true"/>
        <field default="null" name="orderid" type="int(10) unsigned" nullable="false">
            <constraint column="orderid" ondelete="cascade" onupdate="restrict" table="shop_order"/>
        </field>
        <field default="current_timestamp" name="added" type="timestamp" nullable="false"/>
        <field default="null" name="productid" type="int(10) unsigned" nullable="false">
            <constraint column="productid" ondelete="cascade" onupdate="restrict"
                table="shop_product"/>
        </field>
        <field default="0" name="amount" type="float" nullable="false"/>
        <field default="0" name="price" type="float" nullable="false"/>
        <field default="null" name="additionalinfo" type="text" nullable="true"/>
    </table>
</database>

=== fashionweb/moraso/application/plugins/generic/data/dam/.database.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="schema.xsd">
    <table name="dam_asset" engine="InnoDB">
        <field name="assetid" type="int(10) unsigned" default="null" autoincrement="true"
            primary="true"/>
        <field name="typeid" type="int(10) unsigned" default="null"/>
        <field name="identifier" type="varchar(255)" default="null"/>
        <field name="abstract" type="text" default="null"/>
        <field name="copyright" type="varchar(255)" default="null"/>
        <field name="credit" type="varchar(255)" default="null"/>
        <field name="licenseid" type="int(10) unsigned" default="null"/>
        <field name="created" type="timestamp" default="CURRENT_TIMESTAMP"/>
        <field name="modified" type="timestamp" default="0000-00-00 00:00:00"/>
        <field name="validfrom" type="datetime" default="null"/>
        <field name="validuntil" type="datetime" default="null"/>
        <field name="replaces" type="int(10) unsigned" default="null"/>
        <index name="replaces" columns="replaces" unique="false"/>
        <index name="licenseid" columns="licenseid" unique="false"/>
        <index name="typeid" columns="typeid" unique="false"/>
    </table>
    <table name="dam_license" engine="InnoDB">
        <field name="licenseid" type="int(10) unsigned" default="null" autoincrement="true"
            primary="true"/>
        <field name="identifier" type="varchar(255)" default="null"/>
        <field name="description" type="text" default="null"/>
        <field name="url" type="varchar(255)" default="null"/>
    </table>
    <table name="dam_location" engine="InnoDB">
        <field name="locationid" type="int(10) unsigned" default="null" autoincrement="true"
            primary="true"/>
        <field name="countryid" type="int(10) unsigned" default="null"/>
        <field name="city" type="varchar(255)" default="null"/>
        <index name="countryid" columns="countryid" unique="false"/>
    </table>
    <table name="dam_locations" engine="InnoDB">
        <field name="assetid" type="int(10) unsigned" default="null" primary="true"/>
        <field name="locationid" type="int(10) unsigned" default="null" primary="true"/>
        <field name="description" type="text" default="null"/>
        <index name="locationid" columns="locationid" unique="false"/>
    </table>
    <table name="dam_referencedby" engine="InnoDB">
        <field name="assetid" type="int(10) unsigned" default="null" primary="true"/>
        <field name="reference" type="varchar(255)" default="null" primary="true"/>
        <field name="created" type="timestamp" default="CURRENT_TIMESTAMP"/>
    </table>
    <table name="dam_rel" engine="InnoDB">
        <field name="parentid" type="int(10) unsigned" default="null" primary="true"/>
        <field name="childid" type="int(10) unsigned" default="null" primary="true"/>
        <index name="childid" columns="childid" unique="false"/>
    </table>
    <table name="dam_subtype" engine="InnoDB">
        <field name="subtypeid" type="int(10) unsigned" default="null" autoincrement="true"
            primary="true"/>
        <field name="typeid" type="int(10) unsigned" default="null"/>
        <field name="identifier" type="varchar(255)" default="null"/>
        <index name="typeid" columns="typeid" unique="false"/>
    </table>
    <table name="dam_tag" engine="InnoDB">
        <field name="tagid" type="int(10) unsigned" default="null" autoincrement="true"
            primary="true"/>
        <field name="tag" type="varchar(255)" default="null"/>
        <index name="tag" columns="tag" unique="false"/>
    </table>
    <table name="dam_tags" engine="InnoDB">
        <field name="assetid" type="int(10) unsigned" default="null" primary="true"/>
        <field name="tagid" type="int(10) unsigned" default="null" primary="true"/>
        <field name="tagvalue" type="varchar(255)" default="null"/>
        <field name="created" type="timestamp" default="CURRENT_TIMESTAMP"/>
        <index name="tagid" columns="tagid" unique="false"/>
    </table>
    <table name="dam_type" engine="InnoDB">
        <field name="typeid" type="int(10) unsigned" default="null" autoincrement="true"
            primary="true"/>
        <field name="identifier" type="varchar(255)" default="null"/>
        <index name="identifier" columns="identifier" unique="true"/>
    </table>
    <table name="dam_use" engine="InnoDB">
        <field name="useid" type="int(10) unsigned" default="null" autoincrement="true"
            primary="true"/>
        <field name="use" type="varchar(255)" default="null"/>
        <field name="description" type="text" default="null"/>
        <index name="use" columns="use" unique="true"/>
    </table>
    <table name="dam_uses" engine="InnoDB">
        <field name="assetid" type="int(10) unsigned" default="null" primary="true"/>
        <field name="useid" type="int(10) unsigned" default="null" primary="true"/>
        <field name="created" type="timestamp" default="CURRENT_TIMESTAMP"/>
        <index name="useid" columns="useid" unique="false"/>
    </table>
</database>
